
# Week 1: Cleaning and Exploring the Applicant Dataset

**Organization:** NextGenLearners

**Objective:** To explore, clean, and prepare an applicant dataset using Python and Pandas.

In [1]:

import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

In [3]:

from google.colab import files

uploaded = files.upload()

Saving applicants.csv to applicants.csv

In [4]:

import pandas as pd

df = pd.read_csv('applicants.csv')
df.head()

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Awa Jallow,awa.jallow1@example.com,2207000000,Web Development,University of The Gambia,2026-05-01,Under Review
1,Fatou Njie,fatou.njie2@example.com,2207000137,Data Science,AIUWA,2026-05-02,Selected
2,Lamin Jobarteh,lamin.jobarteh3@example.com,2207000274,Cybersecurity,Gambia College,2026-05-03,Rejected
3,Mariama Sowe,mariama.sowe4@example.com,2207000411,UI/UX Design,University of Ghana,2026-05-04,Under Review
4,Ousman Manneh,ousman.manneh5@example.com,2207000548,Mobile App Development,University of Dakar,2026-05-05,Selected

In [5]:

df.shape

(80, 7)

In [6]:

df.head()

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Awa Jallow,awa.jallow1@example.com,2207000000,Web Development,University of The Gambia,2026-05-01,Under Review
1,Fatou Njie,fatou.njie2@example.com,2207000137,Data Science,AIUWA,2026-05-02,Selected
2,Lamin Jobarteh,lamin.jobarteh3@example.com,2207000274,Cybersecurity,Gambia College,2026-05-03,Rejected
3,Mariama Sowe,mariama.sowe4@example.com,2207000411,UI/UX Design,University of Ghana,2026-05-04,Under Review
4,Ousman Manneh,ousman.manneh5@example.com,2207000548,Mobile App Development,University of Dakar,2026-05-05,Selected

In [7]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    79 non-null     object
 1   Email             79 non-null     object
 2   Phone             80 non-null     object
 3   Domain Applied    80 non-null     object
 4   University        79 non-null     object
 5   Application Date  80 non-null     object
 6   Status            79 non-null     object
dtypes: object(7)
memory usage: 4.5+ KB

In [8]:

df.isnull().sum()

Applicant Name      1
Email               1
Phone               0
Domain Applied      0
University          1
Application Date    0
Status              1
dtype: int64

In [9]:

df.duplicated().sum()

np.int64(4)


### Initial Data Exploration Summary

The dataset contains 80 applicant records and
7 columns.

During the initial exploration, four missing
values were identified across Applicant Name,
Email, University, and Status.

Additionally, four exact duplicate records
were detected.

All seven columns are currently stored as
object data types. In particular, Application
Date needs to be converted into a proper
datetime format.

These findings indicate that data cleaning
is necessary before further analysis.

Identify the record with a missing name

In [10]:

df[df['Applicant Name'].isnull()]

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
26,NaN,modou.camara27@example.com,2207003562,Data Science,AIUWA,2026-05-27,Rejected

In [11]:

df = df.dropna(subset=['Applicant Name'])

df.shape

(79, 7)


### Handling Missing Applicant Names

One record was identified with a missing Applicant
Name.

The record was removed because the applicant's
name is essential for identification and record
management.

The dropna() function was used to remove the
record without affecting other valid applicants.

In [12]:

df[df['Email'].isnull()]

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
5,Isatou Touray,NaN,2207000685,Web Development,University of The Gambia,2026-05-06,Rejected

In [13]:

df['Email'] = df['Email'].fillna('Not Provided')

df[df['Applicant Name'] == 'Isatou Touray']

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
5,Isatou Touray,Not Provided,2207000685,Web Development,University of The Gambia,2026-05-06,Rejected

In [14]:

df['Email'] = df['Email'].fillna('Not Provided')

df[df['Applicant Name'] == 'Isatou Touray']

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
5,Isatou Touray,Not Provided,2207000685,Web Development,University of The Gambia,2026-05-06,Rejected


### Handling Missing Email Addresses

One applicant was identified with a missing email
address.

The record was retained because the applicant
had a valid name, phone number, and other
application details.

The missing email was replaced with "Not Provided"
to preserve the applicant's record for analysis.

This placeholder will not be treated as a valid
email address.

In [15]:

df[df['University'].isnull()]

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
8,Ebrima Drammeh,ebrima.drammeh9@example.com,2207001096,UI/UX Design,NaN,2026-05-09,Rejected

In [16]:

df['University'] = df['University'].fillna('Not Specified')

df[df['Applicant Name'] == 'Ebrima Drammeh']

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
8,Ebrima Drammeh,ebrima.drammeh9@example.com,2207001096,UI/UX Design,Not Specified,2026-05-09,Rejected


### Handling Missing University Values

One applicant record contained a missing University
value.

The missing value was replaced with "Not Specified"
because university information is not essential
for identifying the applicant.

This approach preserves the applicant's record
while maintaining consistency in the dataset.

In [17]:

df[df['Status'].isnull()]

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
11,Kaddy Sanneh,kaddy.sanneh12@example.com,2207001507,Data Science,AIUWA,2026-05-12,NaN

In [18]:

df['Status'] = df['Status'].fillna('Under Review')

df[df['Applicant Name'] == 'Kaddy Sanneh']

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
11,Kaddy Sanneh,kaddy.sanneh12@example.com,2207001507,Data Science,AIUWA,2026-05-12,Under Review


### Handling Missing Application Status

One applicant record contained a missing
application status.

The missing value was replaced with "Under Review"
because an unrecorded status may indicate that
the application has not yet been processed.

This approach retains the applicant's record
while providing a consistent default status.

In [19]:

df.isnull().sum()

Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

In [20]:

df.duplicated().sum()

np.int64(4)

In [21]:

df[df.duplicated(keep=False)]

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
3,Mariama Sowe,mariama.sowe4@example.com,2207000411,UI/UX Design,University of Ghana,2026-05-04,Under Review
10,Amadou Camara,amadou.camara11@example.com,2207001370,Web Development,University of The Gambia,2026-05-11,Selected
18,Jainaba Jobarteh,jainaba.jobarteh19@example.com,2207002466,UI/UX Design,University of Ghana,2026-05-19,Under Review
40,Awa Drammeh,awa.drammeh41@example.com,2207005480,Web Development,University of The Gambia,2026-05-13,Selected
76,Mariama Sowe,mariama.sowe4@example.com,2207000411,UI/UX Design,University of Ghana,2026-05-04,Under Review
77,Amadou Camara,amadou.camara11@example.com,2207001370,Web Development,University of The Gambia,2026-05-11,Selected
78,Jainaba Jobarteh,jainaba.jobarteh19@example.com,2207002466,UI/UX Design,University of Ghana,2026-05-19,Under Review
79,Awa Drammeh,awa.drammeh41@example.com,2207005480,Web Development,University of The Gambia,2026-05-13,Selected

In [22]:

# Remove exact duplicate records
df = df.drop_duplicates()

# Check the number of remaining records
df.shape

(75, 7)


### Removing Exact Duplicate Records

Four exact duplicate records were identified
in the dataset.

The drop_duplicates() function was used to
remove these records while retaining the first
occurrence of each applicant.

This prevents duplicate records from affecting
the accuracy of the analysis.

In [23]:

df.duplicated().sum()

np.int64(0)

In [24]:

df['Email'] = df['Email'].str.strip().str.lower()

Check for duplicate email addresses

In [25]:

df['Email'].duplicated().sum()

np.int64(0)

Display applicants sharing an email

In [26]:

valid_email = df['Email'].notna() & (
    df['Email'] != 'not provided'
)

duplicates = df[
    valid_email &
    df['Email'].duplicated(keep=False)
]

duplicates.sort_values('Email')

Empty DataFrame
Columns: [Applicant Name, Email, Phone, Domain Applied, University, Application Date, Status]
Index: []


### Checking for Near-Duplicate Applicants

After removing exact duplicates, email addresses
were standardized by removing extra whitespace
and converting them to lowercase.

The dataset was then examined for applicants
sharing the same email address.

Missing-email placeholders were excluded from
the duplicate comparison to avoid incorrectly
identifying unrelated applicants as duplicates.


### Duplicate Removal Summary

The initial dataset contained four exact duplicate
records, which were successfully removed using
the drop_duplicates() function.

Email addresses were standardized by removing
unnecessary whitespace and converting them to
lowercase.

A further check for near-duplicate applicants
using valid email addresses identified no
additional duplicate records.

The dataset is now free from identified exact
duplicates and email-based near-duplicates.

In [27]:

df['Domain Applied'].unique()

array(['Web Development', 'Data Science', 'Cybersecurity', 'UI/UX Design',
       'Mobile App Development', 'web dev', 'WEB DEV'], dtype=object)

In [28]:

# Remove spaces and standardize capitalization
df['Domain Applied'] = (
    df['Domain Applied'].str.strip().str.lower()
)

# Dictionary for standardizing domain names
domain_mapping = {
    'web dev': 'Web Development',
    'webdev': 'Web Development',
    'web development': 'Web Development',
    'data science': 'Data Science',
    'cybersecurity': 'Cybersecurity',
    'ui/ux design': 'UI/UX Design',
    'mobile app development': 'Mobile App Development'
}

# Apply the mapping
df['Domain Applied'] = df['Domain Applied'].map(domain_mapping)

In [29]:

df['Domain Applied'].unique()

array(['Web Development', 'Data Science', 'Cybersecurity', 'UI/UX Design',
       'Mobile App Development'], dtype=object)

In [30]:

df['Domain Applied'].isnull().sum()

np.int64(0)


### Standardizing Internship Domains

The Domain Applied column initially contained
seven unique values, although only five internship
domains were represented.

Inconsistent entries such as "web dev", "WEB DEV",
and "Web Development" were standardized into
"Web Development".

A Python mapping dictionary was used to ensure
consistent naming across all five internship
domains.

This improves the accuracy of grouping, counting,
and analyzing applications by domain.

In [31]:

df['Domain Applied'].unique()

df['Domain Applied'].nunique()

5

In [32]:

df['Status'].unique()

array(['Under Review', 'Selected', 'Rejected', 'selected'], dtype=object)

In [34]:

df['Status'] = df['Status'].str.strip().str.title()

In [35]:

df['Status'].unique()

array(['Under Review', 'Selected', 'Rejected'], dtype=object)

In [36]:

df['Status'].nunique()

3


### Standardizing Application Status

The Status column initially contained four unique
values due to inconsistent capitalization.

The values "Selected" and "selected" represented
the same application status.

The str.strip() and str.title() methods were used
to standardize the entries.

After cleaning, the column should contain only
three valid statuses: Under Review, Selected,
and Rejected.

In [37]:

df['Applicant Name'].head(15)

0             Awa Jallow
1             Fatou Njie
2       Lamin Jobarteh
3           Mariama Sowe
4          Ousman Manneh
5          Isatou Touray
6           Modou Darboe
7            Binta Gibba
8         Ebrima Drammeh
9           Adama Conteh
10         Amadou Camara
11          Kaddy Sanneh
12            Sainey Bah
13             Musa Faye
14          Haddy Ceesay
Name: Applicant Name, dtype: object

Standardizing Applicant Names

In [38]:

df['Applicant Name'] = (
    df['Applicant Name']
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
    .str.title()
)

Verify the cleaning

In [39]:

df['Applicant Name'].head(15)

0         Awa Jallow
1         Fatou Njie
2     Lamin Jobarteh
3       Mariama Sowe
4      Ousman Manneh
5      Isatou Touray
6       Modou Darboe
7        Binta Gibba
8     Ebrima Drammeh
9       Adama Conteh
10     Amadou Camara
11      Kaddy Sanneh
12        Sainey Bah
13         Musa Faye
14      Haddy Ceesay
Name: Applicant Name, dtype: object


### Standardizing Applicant Names

The Applicant Name column was standardized to
ensure consistent formatting.

Leading and trailing whitespace was removed,
multiple spaces were replaced with single spaces,
and names were converted to title case.

This improves data consistency and makes
applicant records easier to read and compare.

Inspect University Names

In [40]:

df['University'].unique()

array(['University of The Gambia', 'AIUWA', 'Gambia College',
       'University of Ghana', 'University of Dakar', 'Not Specified'],
      dtype=object)

Clean unnecessary whitespace

In [41]:

df['University'] = (
    df['University']
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

df['University'].unique()

array(['University of The Gambia', 'AIUWA', 'Gambia College',
       'University of Ghana', 'University of Dakar', 'Not Specified'],
      dtype=object)


### Standardizing University Names

The University column contained six unique values,
including "Not Specified" for missing information.

The values were reviewed for inconsistent spelling
and formatting.

Whitespace cleaning was applied to ensure
consistency while preserving university names
and abbreviations.

Inspect the application dates

In [42]:

df['Application Date'].head(15)

0     2026-05-01
1     2026-05-02
2     2026-05-03
3     2026-05-04
4     2026-05-05
5     2026-05-06
6     2026-05-07
7     2026-05-08
8     2026-05-09
9     2026-05-10
10    2026-05-11
11    2026-05-12
12    2026-05-13
13    2026-05-14
14    2026-05-15
Name: Application Date, dtype: object

Convert Application Date to Datetime

In [43]:

df['Application Date'].unique()

array(['2026-05-01', '2026-05-02', '2026-05-03', '2026-05-04',
       '2026-05-05', '2026-05-06', '2026-05-07', '2026-05-08',
       '2026-05-09', '2026-05-10', '2026-05-11', '2026-05-12',
       '2026-05-13', '2026-05-14', '2026-05-15', '2026-05-16',
       '2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
       '2026-05-21', '2026-05-22', '2026-05-23', '12/05/2026',
       '2026-05-25', '2026-05-26', '2026-05-28', 'not a date',
       '2026-05-24', '2026-05-27'], dtype=object)

Convert the dates

In [44]:

df['Application Date'] = pd.to_datetime(
    df['Application Date'],
    format='mixed',
    errors='coerce'
)

Verify the conversion

In [45]:

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75 entries, 0 to 75
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    75 non-null     object
 1   Email             75 non-null     object
 2   Phone             75 non-null     object
 3   Domain Applied    75 non-null     object
 4   University        75 non-null     object
 5   Application Date  74 non-null     datetime64[ns]
 6   Status            75 non-null     object
dtypes: datetime64[ns](1), object(6)
memory usage: 4.7+ KB

Check for invalid dates

In [46]:

df['Application Date'].isnull().sum()

np.int64(1)

Investigate the Invalid Date

In [47]:

df[df['Application Date'].isnull()]

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
35,Alieu Sowe,alieu.sowe36@example.com,2207004795,Web Development,University of The Gambia,NaT,Rejected


### Investigating Invalid Application Dates

After converting the Application Date column to
datetime, one invalid or unrecognized date was
identified.

The errors='coerce' parameter converted this
value to NaT.

The affected record will be investigated before
deciding whether to correct the date or remove
the record.

In [48]:

# Reload the original dataset
original_df = pd.read_csv('applicants.csv')

# Display the original date for Alieu Sowe
original_df.loc[
    original_df['Applicant Name'] == 'Alieu Sowe',
    ['Applicant Name', 'Application Date']
]

   Applicant Name Application Date
35     Alieu Sowe       not a date


Verify the date is missing
---

In [49]:

df.loc[
    df['Applicant Name'] == 'Alieu Sowe',
    ['Applicant Name', 'Application Date']
]

   Applicant Name Application Date
35     Alieu Sowe              NaT

Verify the date column's data type

In [50]:

df['Application Date'].dtype

dtype('<M8[ns]')


### Handling an Invalid Application Date

One applicant, Alieu Sowe, had an invalid
Application Date recorded as "not a date".

The original dataset was inspected to determine
whether the date could be recovered.

Since no valid date was available, the record
was retained with a missing datetime value (NaT).

This decision preserves the applicant's other
information while avoiding the introduction
of an incorrect or fabricated date.

Cleaning Phone Numbers

In [51]:

df['Phone'].head(20)

0     2207000000
1     2207000137
2     2207000274
3     2207000411
4     2207000548
5     2207000685
6     2207000822
7     2207000959
8     2207001096
9     2207001233
10    2207001370
11    2207001507
12    2207001644
13    2207001781
14    2207001918
15    2207002055
16    2207002192
17    2207002329
18    2207002466
19    2207002603
Name: Phone, dtype: object

In [52]:

df['Phone'].str.contains(
    r'[\s-]',
    regex=True,
    na=False
).sum()

np.int64(1)

Find the Problematic Phone Number

In [53]:

df.loc[
    df['Phone'].str.contains(r'[\s-]', regex=True, na=False),
    ['Applicant Name', 'Phone']
]

   Applicant Name         Phone
20     Awa Manneh  220-700 2740

Verify Awa Manneh's phone number

In [54]:

df.loc[
    df['Applicant Name'] == 'Awa Manneh',
    ['Applicant Name', 'Phone']
]

   Applicant Name         Phone
20     Awa Manneh  220-700 2740

Correct Awa Manneh's phone number

In [55]:

df.loc[df['Applicant Name'] == 'Awa Manneh', 'Phone'] = '2207002740'

# Display the corrected record
df.loc[
    df['Applicant Name'] == 'Awa Manneh',
    ['Applicant Name', 'Phone']
]

   Applicant Name       Phone
20     Awa Manneh  2207002740

Clean the entire Phone column

In [56]:

df['Phone'] = (
    df['Phone']
    .astype(str)
    .str.replace(r'[\s-]', '', regex=True)
)

Verify the result

In [57]:

print("Phone formatting issues remaining:",
      df['Phone'].str.contains(r'[\s-]', regex=True).sum())

print("Awa Manneh's phone number:")
print(df.loc[df['Applicant Name'] == 'Awa Manneh', 'Phone'])

Phone formatting issues remaining: 0
Awa Manneh's phone number:
20    2207002740
Name: Phone, dtype: object

Verify the final dataset

In [58]:

print("FINAL DATA QUALITY REPORT")
print("-------------------------")

print("Total records:", len(df))
print("Total columns:", df.shape[1])
print("Missing values:")
print(df.isnull().sum())

print("\nExact duplicates:", df.duplicated().sum())
print("Unique domains:", df['Domain Applied'].nunique())
print("Unique statuses:", df['Status'].nunique())
print("Date data type:", df['Application Date'].dtype)

FINAL DATA QUALITY REPORT
-------------------------
Total records: 75
Total columns: 7
Missing values:
Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    1
Status              0
dtype: int64

Exact duplicates: 0
Unique domains: 5
Unique statuses: 3
Date data type: datetime64[ns]


## Data Quality Summary

### Initial Dataset
The original dataset contained 80 applicant records
and 7 columns.

### Issues Identified
- Four missing values across four columns.
- Four exact duplicate records.
- Inconsistent domain names and status capitalization.
- One invalid application date.
- Inconsistent phone number formatting.

### Cleaning Actions
- Removed one applicant with a missing name.
- Replaced missing email with "Not Provided".
- Replaced missing university with "Not Specified".
- Replaced missing status with "Under Review".
- Removed four exact duplicate records.
- Standardized domain names into five categories.
- Standardized applicant names and statuses.
- Converted application dates into datetime format.
- Retained one invalid date as NaT.
- Removed spaces and hyphens from phone numbers.

### Final Dataset
The cleaned dataset is expected to contain 75 records
and 7 columns, with no exact duplicates.

One missing application date remains intentionally
because the original value could not be verified.

The dataset is now more consistent and suitable
for further exploratory analysis.

In [4]:

print("Dataset shape:", df.shape)
print("Duplicates:", df.duplicated().sum())
print("Missing values:")
print(df.isnull().sum())

NameError: name 'df' is not defined

In [5]:

import os

print(os.listdir('/content'))

['.config', 'sample_data']

In [6]:

from google.colab import files

uploaded = files.upload()

Saving applicants.csv to applicants.csv

In [7]:

import pandas as pd

df = pd.read_csv('applicants.csv')

print("Dataset loaded successfully!")
print(df.shape)

Dataset loaded successfully!
(80, 7)

In [8]:

import pandas as pd

# 1. Load the original dataset
df = pd.read_csv('applicants.csv')

print("Original dataset:", df.shape)

# 2. Remove records with missing applicant names
df = df.dropna(subset=['Applicant Name']).copy()

# 3. Handle missing values
df['Email'] = df['Email'].fillna('Not Provided')
df['University'] = df['University'].fillna('Not Specified')
df['Status'] = df['Status'].fillna('Under Review')

# 4. Remove exact duplicates
df = df.drop_duplicates().copy()

# 5. Standardize email addresses
df['Email'] = df['Email'].str.strip().str.lower()

# 6. Standardize internship domains
df['Domain Applied'] = (
    df['Domain Applied'].str.strip().str.lower()
)

domain_mapping = {
    'web dev': 'Web Development',
    'webdev': 'Web Development',
    'web development': 'Web Development',
    'data science': 'Data Science',
    'cybersecurity': 'Cybersecurity',
    'ui/ux design': 'UI/UX Design',
    'mobile app development': 'Mobile App Development'
}

df['Domain Applied'] = df['Domain Applied'].map(domain_mapping)

# 7. Standardize application statuses
df['Status'] = df['Status'].str.strip().str.title()

# 8. Standardize applicant names
df['Applicant Name'] = (
    df['Applicant Name']
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
    .str.title()
)

# 9. Standardize university names
df['University'] = (
    df['University']
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

# 10. Convert application dates
df['Application Date'] = pd.to_datetime(
    df['Application Date'],
    format='mixed',
    errors='coerce'
)

# 11. Standardize phone numbers
df['Phone'] = (
    df['Phone']
    .astype(str)
    .str.replace(r'[\s-]', '', regex=True)
)

# 12. Remove duplicate valid emails
valid_email = (
    df['Email'].notna() &
    df['Email'].ne('not provided')
)

df = pd.concat([
    df.loc[valid_email].drop_duplicates(
        subset=['Email'], keep='first'
    ),
    df.loc[~valid_email]
]).sort_index()

# 13. Reset the index
df = df.reset_index(drop=True)

print("Cleaned dataset:", df.shape)
print("Cleaning completed successfully!")

Original dataset: (80, 7)
Cleaned dataset: (75, 7)
Cleaning completed successfully!

Verify Our Results

In [9]:

print("FINAL DATA QUALITY REPORT")
print("-------------------------")

print("Total records:", len(df))
print("Total columns:", df.shape[1])

print("\nMissing values:")
print(df.isnull().sum())

print("\nExact duplicates:", df.duplicated().sum())
print("Unique domains:", df['Domain Applied'].nunique())
print("Unique statuses:", df['Status'].nunique())
print("Date data type:", df['Application Date'].dtype)

print("Phone formatting issues:",
      df['Phone'].str.contains(
          r'[\s-]', regex=True, na=False
      ).sum())

FINAL DATA QUALITY REPORT
-------------------------
Total records: 75
Total columns: 7

Missing values:
Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    1
Status              0
dtype: int64

Exact duplicates: 0
Unique domains: 5
Unique statuses: 3
Date data type: datetime64[ns]
Phone formatting issues: 0

Export and Download

In [10]:

df.to_csv('applicants_cleaned.csv', index=False)

from google.colab import files
files.download('applicants_cleaned.csv')